import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import MainNav from "./components/portfolio/main-nav";

export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     className="dark"
    >
      <body className="min-h-full flex flex-col">
        <MainNav />
        {children}
        </body>
    </html>
  );
}
